# Generated by Django 2.2.6 on 2019-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='stories',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='residence',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
    ]
