# Generated by Django 2.2.6 on 2019-11-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20191105_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='source_site_groups',
            field=models.ManyToManyField(default=None, related_name='properties', to='properties.SourceSiteGroup'),
        ),
    ]
