# Generated by Django 2.2.6 on 2019-11-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_source_site_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalid',
            name='type',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
