# Generated by Django 2.2.6 on 2019-11-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_externalid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='raw_text',
            field=models.TextField(default=''),
        ),
    ]
