# Generated by Django 2.2.6 on 2019-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinformation',
            name='total_due',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='taxinformation',
            name='year',
            field=models.DateField(default=None),
        ),
    ]
