# Generated by Django 2.2.6 on 2019-11-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20191113_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinformation',
            name='year',
            field=models.DateField(default=None, null=True),
        ),
    ]
