# Generated by Django 2.2.6 on 2019-11-21 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20191113_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxinformation',
            name='total_due',
        ),
        migrations.RemoveField(
            model_name='taxinformation',
            name='year',
        ),
        migrations.CreateModel(
            name='TaxYearSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_tax', models.FloatField(default=0.0)),
                ('base_tax', models.FloatField(default=0.0)),
                ('penalty_fees', models.FloatField(default=0.0)),
                ('other_fees', models.FloatField(default=0.0)),
                ('year', models.IntegerField(default=None, null=True)),
                ('tax_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_summary', to='properties.TaxInformation')),
            ],
        ),
    ]
