# Generated by Django 2.2.6 on 2019-11-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20191121_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ManyToManyField(default=None, related_name='properties', to='properties.Owner'),
        ),
        migrations.AlterField(
            model_name='taxyearsummary',
            name='tax_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_summaries', to='properties.TaxInformation'),
        ),
    ]
