# Generated by Django 2.2.6 on 2019-11-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20191123_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='owners',
        ),
    ]
